language: php
dist: bionic

addons:
  apt:
    packages:
      - libssl1.1
      - libssl-dev
      - libuv1
      - libuv0.10
      - libuv-dev


cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  fast_finish: true
  include:
    # all supported PHP versions with lowest dependencies
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    # symfony LTS versions
    - php: 7.4
      env: SYMFONY_REQUIRE="4.4.*"
    # current Symfony major version
    - php: 7.4
      env: SYMFONY_REQUIRE="5.0.*"
    - php: 7.4
      env: SYMFONY_REQUIRE="5.1.*"
    - php: 7.4
      env: SYMFONY_REQUIRE="5.2.*"

before_install:
  # disable xdebug
  - phpenv config-rm xdebug.ini
  # install cassandra extension
  - wget https://gogs.meteo-concept.fr/apt/debian/pool/main/c/cassandra-cpp-driver/cassandra-cpp-driver_2.16.0-1_amd64.deb
  - wget https://gogs.meteo-concept.fr/apt/debian/pool/main/c/cassandra-cpp-driver/cassandra-cpp-driver-dev_2.16.0-1_amd64.deb
  - sudo dpkg -i *.deb
  - wget https://gogs.meteo-concept.fr/apt/cassandra-1.3.2.tgz
  - tar xvzf cassandra-1.3.2.tgz
  - cd cassandra-1.3.2 && phpize && ./configure && make && cd ..
  - echo "extension=$(pwd)/cassandra-1.3.2/modules/cassandra.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # setup composer dependencies
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - bin/coke
  - bin/atoum
